### PR TITLE
Adding new ID Pin API introduced in mioDAQ

### PR DESCRIPTION
**Pull request by tjying95**
### What does this Pull Request accomplish?

Adding new ID Pin API support introduced in mioDAQ. Depends on this PR: [Add new attribute and APIs for mioDAQ ID Pin feature #262](https://github.com/ni/grpc-device-scrapigen/pull/262)
~~Upgrade Python version to use 3.13 due to some packages no longer supporting Python 3.8.~~
~~Pin mypy, mypy-protobuf and types-protobuf versions since their latest versions dropped support for Python 3.8.~~

### Why should this Pull Request be merged?

As part of the changes to support the API in `nidaqmx-python`.

### What testing has been done?

Local build successfully. 
Export can be consumed by `nidaqmx-python`.

### CODE REVIEW

File: source/codegen/validate_examples.py [hunk 1]
```diff
@@ -90,7 +90,7 @@ def _validate_examples(
 
             print(f" -> Running mypy")
             _system(
-                f"poetry run mypy {dir} --check-untyped-defs --ignore-missing-imports{exclude_option}"
+                f"poetry run mypy {dir} --check-untyped-defs --disable-error-code=operator --ignore-missing-imports{exclude_option}"
```
Comment (tjying95) [inline source/codegen/validate_examples.py:93]: Without `--disable-error-code=operator`, these errors will pop up:

```
-- Validating: nifpga
 -> Running black line-length 100
All done! ✨ 🍰 ✨
2 files would be left unchanged.
 -> Running mypy
nifpga_pb2.pyi:620: error: "ValueType" not callable  [operator]
nifpga_pb2.pyi:665: error: "ValueType" not callable  [operator]
nifpga_pb2.pyi:710: error: "ValueType" not callable  [operator]
nifpga_pb2.pyi:755: error: "ValueType" not callable  [operator]
nifpga_pb2.pyi:3735: error: "ValueType" not callable  [operator]
nifpga_pb2.pyi:3780: error: "ValueType" not callable  [operator]
nifpga_pb2.pyi:3825: error: "ValueType" not callable  [operator]
nifpga_pb2.pyi:3870: error: "ValueType" not callable  [operator]
Found 8 errors in 1 file (checked 2 source files)
```

Which seems to be caused by some functions in nifpga having `property` as parameter:

```python
@typing.final
class GetFifoPropertyI32Request(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SESSION_FIELD_NUMBER: builtins.int
    FIFO_FIELD_NUMBER: builtins.int
    PROPERTY_FIELD_NUMBER: builtins.int
    PROPERTY_RAW_FIELD_NUMBER: builtins.int
    fifo: builtins.int
    property: global___FifoProperty.ValueType  # Here
    property_raw: builtins.int
    @property
    def session(self) -> session_pb2.Session: ...
```

Thoughts?

File: .github/workflows/validate_python.yml [hunk 2]
```diff
@@ -27,7 +27,7 @@ jobs:
     - name: Install poetry for validate_examples.py
       uses: abatilo/actions-poetry@v3
       with:
-        poetry-version: 1.2.2
```
Comment (bkeryan) [inline .github/workflows/validate_python.yml:30]: Please do not unpin Poetry. The release of Poetry 2.0 broke enough of our build pipelines as it is.

Our internal build pipelines are currently using Poetry 1.8.x. @mshafer-NI where is this documented? https://dev.azure.com/ni/DevCentral/_wiki/wikis/AppCentral.wiki/70875/Optional-tools-for-uncommon-cases ?

I think it's fine to update Poetry to 1.8.x. Consider doing that in a separate PR.

File: .github/workflows/validate_python.yml [hunk 3]
```diff
@@ -15,7 +15,7 @@ jobs:
     - name: Setup python3
       uses: actions/setup-python@v5
       with:
-        python-version: '3.8.x'
+        python-version: '3.13.x'
```
Comment (bkeryan) [inline .github/workflows/validate_python.yml:18]: Please don't upgrade to 3.13 yet. The rest of our build pipelines are using 3.11 as documented here: https://dev.azure.com/ni/DevCentral/_wiki/wikis/AppCentral.wiki/65903/Python-Getting-Started 

(It's okay to also run tests with older/newer versions, of course.)

Consider upgrading Python in a separate PR.

Cc: @mshafer-NI

File: source/codegen/validate_examples.py (hunk 1 above)
Comment (bkeryan) [reply source/codegen/validate_examples.py:93]: I think your PR does not modify the nifpga API and should not run into this. The fact that you are encountering this issue is a result of the validate_examples workflow's lack of version pinning. If validate_examples used a pyproject.toml and poetry.toml that were checked into Git, then your PR would not error out because a new upstream version was released.

Cc: @reckenro @astarche @maxxboehme @mshafer-NI

File: .github/workflows/validate_python.yml (hunk 2 above)
Comment (mshafer-NI) [reply .github/workflows/validate_python.yml:30]: Yes, that's the only "doc" we have the mentions the version since preference is for devs to use the internal build tooling's "poetry" command since that allows us to bump the version by updating that. PWG is planning to evaluate and adopt 2.0 this year, but it will likely be in C2 or C3 even.

File: source/codegen/validate_examples.py (hunk 1 above)
Comment (bkeryan) [reply source/codegen/validate_examples.py:93]:
```
    property: global___FifoProperty.ValueType  # Here
    property_raw: builtins.int
    @property
    def session(self) -> session_pb2.Session: ...
```

Yeah, that's a naming conflict. Perhaps the protobuf compiler ought to use `@builtins.property`?

You could work around this by updating the grpc-device codegen to automatically handle this by adding an underscore to parameter names where `keyword.iskeyword(name) or name in __builtin__.__dict__`.

Comment (astarche) [reply source/codegen/validate_examples.py:93]: `GetFifoPropertyI32Request` is relatively new, so I wonder if it's possible that it snuck through broken. Otherwise I agree that "new mypy" or "new mypy-protobuf" seem like the likely causes. @tjying95 for your change, you should do whatever it takes to get the change unblocked and get it in. Since it has nothing to do with your code. Your proposal is good with me. Attempting to pin `mypy*` in the `poetry add` statement also might work.

`validate_examples` is an attempt to do structured validation on the examples without the examples themselves depending on additional dev tools (mypy, poetry, etc). So maybe there's a better way to do that like having a shell `pyproject.toml` in source. It also simulates the process of a python user creating a new `grpc-device` project. The [getting started instructions](https://github.com/ni/grpc-device/wiki/Creating-a-gRPC-Client#creating-a-python-grpc-client) are not version pinned. I agree that having locked versions *and automated updates* would be better. I'm not sure about just locking the versions, that's a tougher tradeoff. Updating before release would also work.

I think this actually could be a serious problem. `property` is a common special/restricted keyword, so maybe this is not the only problem we will see. Ideally `protoc` plugins would be able to deal with this, but that's not always the case. I'll try to figure out how we can follow up. FYI @doshirohan @asumit

**Review by astarche — APPROVED** [review]

File: source/codegen/validate_examples.py (hunk 1 above)
Comment (maxxboehme) [reply source/codegen/validate_examples.py:93]: @christag-ni is working on a fix in his PR that uses a pyproject.toml and lock file. We had to prioritize some other work but he will be back to working on finishing up that PR in the next week.

**Review by reckenro — APPROVED** [review]

**Comment by tjying95** [comment]
Seems like `PR / Run CI / build_nilrt / NILRT Cross Compile with GCC 6.3.0 (pull_request)` is failing with "‘uint8_t’ has not been declared" now:

```
...
FAILED: grpc-sideband/CMakeFiles/ni_grpc_sideband.dir/src/sideband_shared_memory.cc.o 
/usr/bin/c++ -D_BUILDING_GRPC_SIDEBAND -I/home/runner/work/grpc-device/grpc-device/build/grpc-sideband -I/home/runner/work/grpc-device/grpc-device/third_party/grpc-sideband/./src -std=c++11 -O3 -DNDEBUG -MD -MT grpc-sideband/CMakeFiles/ni_grpc_sideband.dir/src/sideband_shared_memory.cc.o -MF grpc-sideband/CMakeFiles/ni_grpc_sideband.dir/src/sideband_shared_memory.cc.o.d -o grpc-sideband/CMakeFiles/ni_grpc_sideband.dir/src/sideband_shared_memory.cc.o -c /home/runner/work/grpc-device/grpc-device/third_party/grpc-sideband/src/sideband_shared_memory.cc
In file included from /home/runner/work/grpc-device/grpc-device/third_party/grpc-sideband/src/sideband_shared_memory.cc:5:
/home/runner/work/grpc-device/grpc-device/third_party/grpc-sideband/./src/sideband_data.h:48:61: error: ‘uint8_t’ has not been declared
   48 | int32_t _SIDEBAND_FUNC WriteSidebandData(int64_t dataToken, uint8_t* bytes, int64_t bytecount);
      |                                                             ^~~~~~~
/home/runner/work/grpc-device/grpc-device/third_party/grpc-sideband/./src/sideband_data.h:49:60: error: ‘uint8_t’ has not been declared
   49 | int32_t _SIDEBAND_FUNC ReadSidebandData(int64_t dataToken, uint8_t* bytes, int64_t bufferSize, int64_t* numBytesRead);
      |                                                            ^~~~~~~
...
```

Did some submodules got upgraded as well?

**Comment by tjying95** [comment]
> Seems like `PR / Run CI / build_nilrt / NILRT Cross Compile with GCC 6.3.0 (pull_request)` is failing with "‘uint8_t’ has not been declared" now:
> 
> ```
> ...
> FAILED: grpc-sideband/CMakeFiles/ni_grpc_sideband.dir/src/sideband_shared_memory.cc.o 
> /usr/bin/c++ -D_BUILDING_GRPC_SIDEBAND -I/home/runner/work/grpc-device/grpc-device/build/grpc-sideband -I/home/runner/work/grpc-device/grpc-device/third_party/grpc-sideband/./src -std=c++11 -O3 -DNDEBUG -MD -MT grpc-sideband/CMakeFiles/ni_grpc_sideband.dir/src/sideband_shared_memory.cc.o -MF grpc-sideband/CMakeFiles/ni_grpc_sideband.dir/src/sideband_shared_memory.cc.o.d -o grpc-sideband/CMakeFiles/ni_grpc_sideband.dir/src/sideband_shared_memory.cc.o -c /home/runner/work/grpc-device/grpc-device/third_party/grpc-sideband/src/sideband_shared_memory.cc
> In file included from /home/runner/work/grpc-device/grpc-device/third_party/grpc-sideband/src/sideband_shared_memory.cc:5:
> /home/runner/work/grpc-device/grpc-device/third_party/grpc-sideband/./src/sideband_data.h:48:61: error: ‘uint8_t’ has not been declared
>    48 | int32_t _SIDEBAND_FUNC WriteSidebandData(int64_t dataToken, uint8_t* bytes, int64_t bytecount);
>       |                                                             ^~~~~~~
> /home/runner/work/grpc-device/grpc-device/third_party/grpc-sideband/./src/sideband_data.h:49:60: error: ‘uint8_t’ has not been declared
>    49 | int32_t _SIDEBAND_FUNC ReadSidebandData(int64_t dataToken, uint8_t* bytes, int64_t bufferSize, int64_t* numBytesRead);
>       |                                                            ^~~~~~~
> ...
> ```
> 
> Did some submodules got upgraded as well?

I tried building `grpc-device` by itself, seems working, seems working on windows and I believe non-cross-compiling linux.
I tried following the steps in `build_nilrt.yml` in an Ubuntu VM, can't get that to work yet.

Any idea? @bkeryan @zhindes

**Comment by zhindes** [comment]
> > Seems like `PR / Run CI / build_nilrt / NILRT Cross Compile with GCC 6.3.0 (pull_request)` is failing with "‘uint8_t’ has not been declared" now:
> > ```
> > ...
> > FAILED: grpc-sideband/CMakeFiles/ni_grpc_sideband.dir/src/sideband_shared_memory.cc.o 
> > /usr/bin/c++ -D_BUILDING_GRPC_SIDEBAND -I/home/runner/work/grpc-device/grpc-device/build/grpc-sideband -I/home/runner/work/grpc-device/grpc-device/third_party/grpc-sideband/./src -std=c++11 -O3 -DNDEBUG -MD -MT grpc-sideband/CMakeFiles/ni_grpc_sideband.dir/src/sideband_shared_memory.cc.o -MF grpc-sideband/CMakeFiles/ni_grpc_sideband.dir/src/sideband_shared_memory.cc.o.d -o grpc-sideband/CMakeFiles/ni_grpc_sideband.dir/src/sideband_shared_memory.cc.o -c /home/runner/work/grpc-device/grpc-device/third_party/grpc-sideband/src/sideband_shared_memory.cc
> > In file included from /home/runner/work/grpc-device/grpc-device/third_party/grpc-sideband/src/sideband_shared_memory.cc:5:
> > /home/runner/work/grpc-device/grpc-device/third_party/grpc-sideband/./src/sideband_data.h:48:61: error: ‘uint8_t’ has not been declared
> >    48 | int32_t _SIDEBAND_FUNC WriteSidebandData(int64_t dataToken, uint8_t* bytes, int64_t bytecount);
> >       |                                                             ^~~~~~~
> > /home/runner/work/grpc-device/grpc-device/third_party/grpc-sideband/./src/sideband_data.h:49:60: error: ‘uint8_t’ has not been declared
> >    49 | int32_t _SIDEBAND_FUNC ReadSidebandData(int64_t dataToken, uint8_t* bytes, int64_t bufferSize, int64_t* numBytesRead);
> >       |                                                            ^~~~~~~
> > ...
> > ```

> > Did some submodules got upgraded as well?
> 
> I tried building `grpc-device` by itself, seems working, seems working on windows and I believe non-cross-compiling linux. I tried following the steps in `build_nilrt.yml` in an Ubuntu VM, can't get that to work yet.
> 
> Any idea? @bkeryan @zhindes

I got nothing... maybe @astarche or @reckenro would know? I'm not a maintainer or active here :(

**Comment by maxxboehme** [comment]
> > Seems like `PR / Run CI / build_nilrt / NILRT Cross Compile with GCC 6.3.0 (pull_request)` is failing with "‘uint8_t’ has not been declared" now:
> > ```
> > ...
> > FAILED: grpc-sideband/CMakeFiles/ni_grpc_sideband.dir/src/sideband_shared_memory.cc.o 
> > /usr/bin/c++ -D_BUILDING_GRPC_SIDEBAND -I/home/runner/work/grpc-device/grpc-device/build/grpc-sideband -I/home/runner/work/grpc-device/grpc-device/third_party/grpc-sideband/./src -std=c++11 -O3 -DNDEBUG -MD -MT grpc-sideband/CMakeFiles/ni_grpc_sideband.dir/src/sideband_shared_memory.cc.o -MF grpc-sideband/CMakeFiles/ni_grpc_sideband.dir/src/sideband_shared_memory.cc.o.d -o grpc-sideband/CMakeFiles/ni_grpc_sideband.dir/src/sideband_shared_memory.cc.o -c /home/runner/work/grpc-device/grpc-device/third_party/grpc-sideband/src/sideband_shared_memory.cc
> > In file included from /home/runner/work/grpc-device/grpc-device/third_party/grpc-sideband/src/sideband_shared_memory.cc:5:
> > /home/runner/work/grpc-device/grpc-device/third_party/grpc-sideband/./src/sideband_data.h:48:61: error: ‘uint8_t’ has not been declared
> >    48 | int32_t _SIDEBAND_FUNC WriteSidebandData(int64_t dataToken, uint8_t* bytes, int64_t bytecount);
> >       |                                                             ^~~~~~~
> > /home/runner/work/grpc-device/grpc-device/third_party/grpc-sideband/./src/sideband_data.h:49:60: error: ‘uint8_t’ has not been declared
> >    49 | int32_t _SIDEBAND_FUNC ReadSidebandData(int64_t dataToken, uint8_t* bytes, int64_t bufferSize, int64_t* numBytesRead);
> >       |                                                            ^~~~~~~
> > ...
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Did some submodules got upgraded as well?
> 
> I tried building `grpc-device` by itself, seems working, seems working on windows and I believe non-cross-compiling linux. I tried following the steps in `build_nilrt.yml` in an Ubuntu VM, can't get that to work yet.
> 
> Any idea? @bkeryan @zhindes

The grpc-sideband dependency hasn't been updated in about 4 months not sure why it would start failing now especially with an error about that datatype.

**Comment by bkeryan** [comment]
> Seems like `PR / Run CI / build_nilrt / NILRT Cross Compile with GCC 6.3.0 (pull_request)` is failing with "‘uint8_t’ has not been declared" now:
> 
> ```
> ...
> FAILED: grpc-sideband/CMakeFiles/ni_grpc_sideband.dir/src/sideband_shared_memory.cc.o 
> /usr/bin/c++ -D_BUILDING_GRPC_SIDEBAND -I/home/runner/work/grpc-device/grpc-device/build/grpc-sideband -I/home/runner/work/grpc-device/grpc-device/third_party/grpc-sideband/./src -std=c++11 -O3 -DNDEBUG -MD -MT grpc-sideband/CMakeFiles/ni_grpc_sideband.dir/src/sideband_shared_memory.cc.o -MF grpc-sideband/CMakeFiles/ni_grpc_sideband.dir/src/sideband_shared_memory.cc.o.d -o grpc-sideband/CMakeFiles/ni_grpc_sideband.dir/src/sideband_shared_memory.cc.o -c /home/runner/work/grpc-device/grpc-device/third_party/grpc-sideband/src/sideband_shared_memory.cc
> In file included from /home/runner/work/grpc-device/grpc-device/third_party/grpc-sideband/src/sideband_shared_memory.cc:5:
> /home/runner/work/grpc-device/grpc-device/third_party/grpc-sideband/./src/sideband_data.h:48:61: error: ‘uint8_t’ has not been declared
>    48 | int32_t _SIDEBAND_FUNC WriteSidebandData(int64_t dataToken, uint8_t* bytes, int64_t bytecount);
>       |                                                             ^~~~~~~
> /home/runner/work/grpc-device/grpc-device/third_party/grpc-sideband/./src/sideband_data.h:49:60: error: ‘uint8_t’ has not been declared
>    49 | int32_t _SIDEBAND_FUNC ReadSidebandData(int64_t dataToken, uint8_t* bytes, int64_t bufferSize, int64_t* numBytesRead);
>       |                                                            ^~~~~~~
> ...
> ```

The build should be fixed now, thanks to #1155 and #1151 

You need to resolve merge conflicts before the PR checks will run again.
